lib/Gitlab/Client.php, lib/Gitlab/HttpClient/Listener/AuthListener.php
http://doc.gitlab.com/ce/integration/oauth_provider.html
=> Added the ability to authenticate using an OAuth token

lib/Gitlab/Model/ProjectNamespace.php
The name property was omitted from the Namespace model
=> Namespace as name property

lib/Gitlab/Model/MergeRequest.php
Hey there,
Ran into an issue running Gitlab 7.10 where description was coming back from the API for merge requests, but description was not in the list of properties in Gitlab\Model\MergeRequest. As a result, Gitlab\Model\MergeRequest::fromArray (calling Gitlab\Model\AbstractModel::hydrate) was throwing an exception.
This pull request adds the description key to the list of properties in Gitlab\Model\MergeRequest.
It looks like the current documentation for the Gitlab API lists description as a field, so this shouldn't be a old API version issue, probably will be this way going forward. The list of properties I referenced is available here for review: http://doc.gitlab.com/ee/api/merge_requests.html#get-single-mr
Hope this helps!
Take care,
JB
=> Add description field to the MergeRequest model

lib/Gitlab/Model/Note.php
In [gushphp/gush](https://github.com/gushphp/gush), we need to access the comment `id`. The simplest way is to use the `Model` definition to map loaded data.
It's a really simple PR but it'll allow to simplify our code :smile:.
=> Allow to access `Note` id through `__get`

lib/Gitlab/Model/ProjectHook.php
Since the merging of GitLab and GitLab CI, project web hooks now have an additional `build_events` property attached to them.
=> add build_events to project hooks

lib/Gitlab/Model/Project.php
Invalid variable name on the project->keys() function.
=> Minor bug fix in the keys() function on a project.

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
Adds the newer merge request notes endpoint. The notes endpoint is the preferred endpoint to get comments, and returns more data than the old comments endpoint.
=> Adding the newer merge request notes API endpoint.

lib/Gitlab/Api/Issues.php
As per the latest docs, a milestone title can be passed as an argument to filter the issues by that milestone (http://docs.gitlab.com/ee/api/issues.html#list-project-issues)
This adds a milestone key to the array of allowed params.
=> Added support for milestone filter

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
Get a single build of a project.
Get a trace of a specific build of a project.
=> Add build and trace to Project API

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
Adds support for CRUD functionality on a projects' build variables. Tested with unit tests and Gitlab version 8.10.2.
Fixes issue #127
=> Add support for build variables

composer.json
ext-xml is required by utf_encode() used in this library
=> Add missing requirement for PHP's XML extension

lib/Gitlab/Api/MergeRequests.php
By default the API only return the 20 last entries.
Allow to paginate for retrieve more historical data.
=> allow to paginate merge request notes

lib/Gitlab/Api/MergeRequests.php
Add a new method to retrieve merge requests commits: http://docs.gitlab.com/ce/api/merge_requests.html#get-single-mr-commits
=> Allow to retrieve Merge Requests commits

lib/Gitlab/Api/Projects.php
Gitlab API has the ability to fork a project: http://docs.gitlab.com/ce/api/projects.html#fork-project
This PR just implement that feature...
=> Allow to fork a repository in current namespace

lib/Gitlab/Api/Repositories.php, test/Gitlab/Tests/Api/RepositoriesTest.php
I couldn't find these APIs, so I've added them :)
Documented [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/api/tags.md#create-a-new-release) and [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/api/tags.md#update-a-release).
Also added unit tests.
/cc @m4tthumphrey
=> Added API for creating/updating a tag release

lib/Gitlab/Api/Users.php, test/Gitlab/Tests/Api/UsersTest.php
Added 
- listing of all emails (current user)
- method for getting specific email by id (current user)
- tests for both
see https://docs.gitlab.com/ce/api/users.html#list-emails
=> Add user email listing

lib/Gitlab/Api/DeployKeys.php, lib/Gitlab/Api/Projects.php, lib/Gitlab/Client.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Api/DeployKeysTest.php, test/Gitlab/Tests/Api/ProjectsTest.php
* Add `DeployKeys` to retrieve all available deploy keys
* Add API to enable a key for a project
* Add API to disable a key for a project
=> Add deploy keys related API

lib/Gitlab/Api/Issues.php
For now, we can only add and update comments.
This PR adds the ability to delete a comment.
=> Add ability to delete an issue comment

lib/Gitlab/Api/Projects.php
I needed the deploy keys for a given project. So I implemented it according to the [documentation](https://docs.gitlab.com/ce/api/deploy_keys.html#list-project-deploy-keys).
=> Add deploy keys to projects api

lib/Gitlab/Api/Repositories.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Api/RepositoriesTest.php
File api calls allow 2 additional optional parameters: `author_email` and `author_name`
GitLab documentation for the calls: https://docs.gitlab.com/ee/api/repository_files.html
=> File: allow autor for create/update/delete

lib/Gitlab/Client.php
There is currently no way to change the timeout for the Curl client. Only way to do so is by setting a new client.
Current way:
```php
$client = new \Gitlab\Client('https://gitlab.com/api/v3/');
$client->setOption('timeout', 1);
$client->setHttpClient(new HttpClient($client->getBaseUrl(), ['timeout' => 1], $curl));
```
Once this PR is merged you can simply do:
```php
$client = new \Gitlab\Client('https://gitlab.com/api/v3/', null, ['timeout' => 1]);
```
=> Client: allow usage of options

lib/Gitlab/Api/Keys.php, lib/Gitlab/Client.php, test/Gitlab/Tests/Api/KeysTest.php
Add a endpoint to search by a key id. 
```php
$client = new \Gitlab\Client(GITLAB_URL);
$client->authenticate(GITLAB_KEY, \Gitlab\Client::AUTH_URL_TOKEN);
$key = $client->api('keys')->show(1); 
/*
{
"id" : 1,
"title" : "A key",
"key" : "key",
"created_at" : "2016-01-01T01:00:00.000Z",
"user" : {
...
} 
}
*/
```
=> Add keys endpoint "/keys/:id"

lib/Gitlab/Api/Tags.php, lib/Gitlab/Client.php, test/Gitlab/Tests/Api/ProjectsTest.php, test/Gitlab/Tests/Api/TagsTest.php
=> Add tags API

lib/Gitlab/Api/Repositories.php
Allowing different archive format types. Backwards compatible as default is `tar.gz` which is what was the default before.
Correcting incorrect comment about "content" key in array too.
=> Allowing different archive format types

lib/Gitlab/Api/AbstractApi.php, lib/Gitlab/Api/Jobs.php, lib/Gitlab/Client.php, lib/Gitlab/Model/Job.php, lib/Gitlab/Model/Pipeline.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Api/JobsTest.php, test/Gitlab/Tests/Api/TestCase.php
Hey guys,
Here is a PR to add support for the Jobs API (https://docs.gitlab.com/ce/api/jobs.html)
I wrote this PR because I needed a way to download artifacts files. This should replace the PR #164 that is based on old APIs methods that are no more documented.
One important point: since php-gitlab-api uses Buzz (until #191 is closed), I used Buzz to fetch the files. Buzz does not have the notion of streams... so the whole artifacts file is loaded into a PHP string. This is ok for relatively small files, but if you have an artifacts file that is a gigabyte large, this will certainly be a problem.
Should php-gitlab-api migrate to http-client (please do!), I highly recommend adding additional methods in the Jobs class like: `artifactsAsStream` that returns a stream instead of a string. This …
=> Adding the Jobs API

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
Hello @m4tthumphrey ,
It lacks what to for approve or know the state of approval, here is a PR to add these features:
* https://docs.gitlab.com/ee/api/merge_requests.html#merge-request-approvals
* https://docs.gitlab.com/ee/api/merge_requests.html#approve-merge-request
* https://docs.gitlab.com/ee/api/merge_requests.html#unapprove-merge-request
Regards
=> Add approvals, approve & unapprove API's

lib/Gitlab/Api/Issues.php, test/Gitlab/Tests/Api/IssuesTest.php
Changes for [!8967](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8967)
=> update show issue for v4

UPGRADE.md, lib/Gitlab/Api/Issues.php
Changes for [!9530](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9530)
=> Use issue iid in all issues related endpoints

UPGRADE.md, lib/Gitlab/Api/Groups.php, test/Gitlab/Tests/Api/GroupsTest.php
Changes for [!9337](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9337)
=> replace visibility_level by visibility

UPGRADE.md, composer.json, lib/Gitlab/Api/AbstractApi.php, lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
This contains changes for [!8962](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8962), [!8877](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8877) and [!9674](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9674).
I introduced the `OptionsResolver` to validate and sanitize parameters. If we agree with this, the same pattern could be applied everywhere.
=> Projects collection consolidation

UPGRADE.md, lib/Gitlab/Api/AbstractApi.php, lib/Gitlab/Api/MergeRequests.php, lib/Gitlab/HttpClient/Message/QueryStringBuilder.php, test/Gitlab/Tests/Api/MergeRequestsTest.php, test/Gitlab/Tests/HttpClient/Message/QueryStringBuilderTest.php
This carry changes for [!8793](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8793).
I introduced a QueryStringBuilder class to replace `http_build_query`. The only difference is that indexed arrays are encoded using `[]` instead of `[0]`.
=> Update MergeRequestsApi for V4 compatibility

.travis.yml, lib/Gitlab/Api/IssueBoards.php, lib/Gitlab/Api/Users.php, lib/Gitlab/Client.php, lib/Gitlab/HttpClient/Builder.php, lib/Gitlab/Model/Branch.php, lib/Gitlab/Model/Group.php, lib/Gitlab/Model/Hook.php, lib/Gitlab/Model/Issue.php, lib/Gitlab/Model/MergeRequest.php, lib/Gitlab/Model/Milestone.php, lib/Gitlab/Model/Pipeline.php, lib/Gitlab/Model/Project.php, lib/Gitlab/Model/ProjectHook.php, lib/Gitlab/Model/Session.php, lib/Gitlab/Model/Snippet.php, lib/Gitlab/Model/User.php
This fix level 4 errors reported by https://github.com/phpstan/phpstan.
This improve code safety.
I introduced explicit methods to get API endpoints in the Client. In near future, we could deprecate the `api` and `__get` magic methods from `Gitlab\Client` which does not add any value.
phpstan is now run on travis-ci.
=> Static analysis

UPGRADE.md, lib/Gitlab/Api/AbstractApi.php, lib/Gitlab/Api/DeployKeys.php, lib/Gitlab/Api/Groups.php, lib/Gitlab/Api/IssueBoards.php, lib/Gitlab/Api/Issues.php, lib/Gitlab/Api/Jobs.php, lib/Gitlab/Api/MergeRequests.php, lib/Gitlab/Api/Milestones.php, lib/Gitlab/Api/ProjectNamespaces.php, lib/Gitlab/Api/Projects.php, lib/Gitlab/Api/Repositories.php, lib/Gitlab/Api/Users.php, lib/Gitlab/Model/Branch.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Api/DeployKeysTest.php, test/Gitlab/Tests/Api/GroupsTest.php, test/Gitlab/Tests/Api/IssueBoardsTest.php, test/Gitlab/Tests/Api/IssuesTest.php, test/Gitlab/Tests/Api/JobsTest.php, test/Gitlab/Tests/Api/ProjectNamespacesTest.php, test/Gitlab/Tests/Api/ProjectsTest.php, test/Gitlab/Tests/Api/RepositoriesTest.php, test/Gitlab/Tests/Api/UsersTest.php
This force usage of `OptionsResolver` only where it would break BC. It may be used later in other methods without breaking.
This improve a lot the API quality by avoiding endless method signatures. All the updated methods have their arguments in sync with current v4 API.
This also fix #186.
This is probably better reviewed commit per commit instead of a whole.
=> Use options resolver almost everywhere

lib/Gitlab/Api/AbstractApi.php, lib/Gitlab/Api/Repositories.php, test/Gitlab/Tests/Api/RepositoriesTest.php
This add [multi file commit](https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions) method.
Fix #209 and close #158.
=> Multi files commit

lib/Gitlab/HttpClient/Message/QueryStringBuilder.php, test/Gitlab/Tests/HttpClient/Message/QueryStringBuilderTest.php
The `QueryStringBuilder` has a bug with encoding the `false` value.
See https://3v4l.org/r4Sqt for the `http_build_query` behavior.
=> Fix false boolean query string encoding

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
Comments have been removed in V4. We should use notes api instead.
=> Deprecate merge request comment related methods

lib/Gitlab/Model/MergeRequest.php
* Adjusted the model to use the iid instead of id.
=> #242 Gitlab/Model/MergeRequest methods fails on incorrect id usage

lib/Gitlab/Api/Issues.php
Adds support for the 'scope' parameter introduced in GitLab 9.5 [See Issue API](https://docs.gitlab.com/ee/api/issues.html)
=> Issues API: Add support for 'scope' parameter

lib/Gitlab/Model/Milestone.php
`MIlestone` property `start_date` was missed. Documentation: https://docs.gitlab.com/ce/api/milestones.html
This property exists in both v3 and v4 APIs.
=> Added missing property 'start_date' to Milestone model

lib/Gitlab/Model/Issue.php
need the `iid` (not the `id`) for `show()` and `update()`.
See also:
- for show: https://docs.gitlab.com/ee/api/issues.html#single-issue
- for update: https://docs.gitlab.com/ee/api/issues.html#edit-issue
=> Issues API: Bugfixing in update and show an issue (Issue: #254)

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
updated `addVariable()` and `updateVariable()` to match current gitlab api (added `$protected `$environment_scope`)
- https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable
- https://docs.gitlab.com/ee/api/project_level_variables.html#update-variable
=> Updated addVariable() and updateVariable()

composer.json
Without ext-xml a fatal error can occur because of the absence of utf8_encode().
Fixes #260
=> Add ext-xml as a dependency

lib/Gitlab/Api/Projects.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Api/ProjectsTest.php
Closes #264 
The `can_push` option is set to false as default like the GitLab API behavior.
IMHO, it should be released on a patch version because it's a missing option fix.
=> Add can_push option to deploy key creation

lib/Gitlab/Api/Repositories.php, test/Gitlab/Tests/Api/RepositoriesTest.php
Hello.
This is my attempt to fix #263.
I tested only `Delete branch` endpoint, cause this is the only one we are using here right now.
I completely removed `encodeBranch` function being guided by #86 pull request, which we kinda reverting now.
upd:
by "tested" i mean on real gitlab installation, not just unit.
=> Branches containing a slash break v4 branch endpoints. #263

lib/Gitlab/Model/Project.php
Parameter target_project_id must be filled otherwise if it is null gitlab returns 500 internal server error
=> Create merge request 500 error fix

lib/Gitlab/Api/Groups.php, lib/Gitlab/Api/MergeRequests.php, lib/Gitlab/Api/Projects.php, lib/Gitlab/Api/Repositories.php, lib/Gitlab/Api/Users.php, test/Gitlab/Tests/Api/GroupsTest.php, test/Gitlab/Tests/Api/MergeRequestsTest.php, test/Gitlab/Tests/Api/ProjectsTest.php, test/Gitlab/Tests/Api/RepositoriesTest.php, test/Gitlab/Tests/Api/UsersTest.php
This fix also addresses issues with several boolean normalizers, that always normalized to true.
close #262
=> fix issues with symfony options resolver

composer.json, lib/Gitlab/HttpClient/Builder.php
This is a minor change that we need to do in increase the developer experience for Symfony users. This will make our custom plugins visible in the Symfony debug toolbar.
---
Related to https://github.com/KnpLabs/php-github-api/pull/687.
=> Use the plugin client factory in the http client builder

lib/Gitlab/Model/Issue.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Model/IssueTest.php
Hello,
This MR is related to #229 and fix the following use case : 
```php
<?php
$client = \Gitlab\Client::create('http://mygitlab.com')->authenticate('myToken',\Gitlab\Client::AUTH_URL_TOKEN);
$project = new Project(31,$client);
$project->closeIssue(1,"this is the end"); // iid is use as identifier in https://github.com/cube43/php-gitlab-api/blob/067b183b07f86caadd3662a681f61406ffa3d3a5/lib/Gitlab/Model/Issue.php#L94
$project->openIssue(1); // iid is use as identifier in https://github.com/cube43/php-gitlab-api/blob/067b183b07f86caadd3662a681f61406ffa3d3a5/lib/Gitlab/Model/Issue.php#L94
$project->updateIssue(2,array('assignee_id'=>1)); // iid is use as identifier in https://github.com/cube43/php-gitlab-api/blob/067b183b07f86caadd3662a681f61406ffa3d3a5/lib/Gitlab/Model/Issue.php#L94 …
```
=> iid instead of id in issue contruct

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
GitLab API per default defines 20 items per_page for the returned result. Now if a project has more than 20 members we have an issue with increasing the number of items to max i.e. 100.
Therefore I complemented your code.
Many thanks!
=> Pagination of Project Members

lib/Gitlab/Api/Jobs.php
In the method `artifactsByRefName()` the $job_name is not encoded.
I guess that should be done to avoid errors
=> encode $job_name

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
After the merge of #281 I realized that we don't need the validation of the parameters "page" and "per_page" since it will be validated by the gitlab api itself.
Therefore I removed the validation and default values for these parameters but also added a test for getting the project members with pagination.
@m1guelpf  Sorry that I've noticed only now.
=> removed pagination parameters default values and validation for project members

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
to include:
- statistics
- custom attributes
=> add parameters to project

lib/Gitlab/Api/AbstractApi.php, test/Gitlab/Tests/Api/AbstractApiTest.php
Replace http_build_query to avoid issues with array parameters.
For example : 
```
$merge_request = new GitlabMergeRequest(
[...]
);
$merge_request = $merge_request->show();
$merge_request->update([
'labels' => ['Needs review']
]);
```
will currently return an "invalid labels" error.
=> Use QueryStringBuilder in AbstractAPI::put

lib/Gitlab/Api/Groups.php, test/Gitlab/Tests/Api/GroupsTest.php
This PR will add additional fields (optionally) as described here: https://docs.gitlab.com/ce/api/groups.html#new-group
I had to "filter" out `null` values as it would else return a 500 from gitlab.com. `description` is optional anyways, so it can be removed if `null`.
=> Extend create groups api

lib/Gitlab/Api/Environments.php, lib/Gitlab/Client.php, test/Gitlab/Tests/Api/EnvironmentsTest.php
the delete function only deletes the environment from the gitlab-database.
the stop function executes the stop action, defined in the gitlab ci yml for the environment.
=> add environment & deployment class to api + add stop environment function

lib/Gitlab/Api/Users.php, test/Gitlab/Tests/Api/UsersTest.php
This adds integrations for:
- https://docs.gitlab.com/ce/api/users.html#list-emails-for-user
- https://docs.gitlab.com/ce/api/users.html#add-email-for-user
- https://docs.gitlab.com/ce/api/users.html#delete-email-for-given-user
=> Add methods for managing emails for users

test/Gitlab/Tests/HttpClient/BuilderTest.php
I found this while working on #351 
Before this change I got this while running phpunit:
```
There were 3 warnings:
1) Gitlab\Tests\HttpClient\BuilderTest::testAddPluginShouldInvalidateHttpClient
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
2) Gitlab\Tests\HttpClient\BuilderTest::testRemovePluginShouldInvalidateHttpClient
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
3) Gitlab\Tests\HttpClient\BuilderTest::testHttpClientShouldBeAnHttpMethodsClient
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or …
```
=> Upgrade the BuilderTest to use getMockBuilder and not the deprecated getMock function

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
The new fields are:
updated_after
updated_before
scope
author_id
assignee_id
sourche_branch
target_branch
(I added more fields in the test because they where in the class but not in the test)
See https://docs.gitlab.com/ce/api/merge_requests.html#list-project-merge-requests for more details
=> Add the more paremeters to the MergeRequests api call

lib/Gitlab/Api/IssueBoards.php, lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/IssueBoardsTest.php
Couldn't get all the labels of a project due to the default limit of 20 per page.
Now we can pass optional paramaters to get project labels
ex: $parameters = ['page'=>1, 'per_page'=>100];
=> Add parameters to get project labels

lib/Gitlab/Api/IssueBoards.php, lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/IssueBoardsTest.php
These 4 methods were missing from the IssueBoards class:
- show (https://docs.gitlab.com/ee/api/boards.html#single-board)
- create (https://docs.gitlab.com/ee/api/boards.html#create-a-board)
- update (https://docs.gitlab.com/ee/api/boards.html#update-a-board)
- remove (https://docs.gitlab.com/ee/api/boards.html#delete-a-board)
I also added the corresponding unit tests
=> Add crud methods to issue boards

doc/customize.md
Fixes class name in example code.
=> Correct Guzzle6 client example

lib/Gitlab/Api/Repositories.php, test/Gitlab/Tests/Api/ProjectsTest.php, test/Gitlab/Tests/Api/RepositoriesTest.php
Adds support for an API endpoint GitLab added recently—https://docs.gitlab.com/ce/api/repositories.html#merge-base
=> Add repository merge base API support

lib/Gitlab/Api/Tags.php, test/Gitlab/Tests/Api/TagsTest.php
Add missing Release support
https://docs.gitlab.com/ee/api/tags.html#create-a-new-release
example of usage:
`$client->tags()->createRelease($projectId, urlencode($tagName), [
'description' => $description,
])`
`$client->tags()->updateRelease($projectId, urlencode($tagName), [
'description' => $description,
]);`
=> Add missing Release support

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
This implements another project transfer API: https://docs.gitlab.com/ce/api/projects.html#transfer-a-project-to-a-new-namespace
This was added by https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/20122, seems like permissions might be different from the other ways to transfer a project.
(For our instance of GitLab, this API returns normally. While `…->api('groups')->transfer(…)` does transfer the project, but the HTTP request times out.)
=> Implement project transfer API

lib/Gitlab/Api/Users.php, test/Gitlab/Tests/Api/UsersTest.php
GitLab 11.4 added a new parameter to the Add email for user API: https://docs.gitlab.com/ce/api/users.html#add-email-for-user
=> Add $skip_confirmation parameter to Users::createEmailForUser()

lib/Gitlab/Api/Issues.php, lib/Gitlab/Model/Issue.php, test/Gitlab/Tests/Api/IssuesTest.php, test/Gitlab/Tests/Model/IssueTest.php
Adds the ability to move an issue from a project to another one, referring to this part of the [GitLab API documentation](https://docs.gitlab.com/ee/api/issues.html#move-an-issue).
=> Implements move issue API endpoint.

lib/Gitlab/Api/AbstractApi.php, lib/Gitlab/Api/Users.php, test/Gitlab/Tests/Api/UsersTest.php
This adds support for uploading a user's avatar via a new files argument. It works like `…->update(…, array('avatar' => 'path/to/avatar'))`
The code in `AbstractApi::put()` is copied from `AbstractApi::post()`.
I wasn’t able to find any existing testing of file uploads. Please let me know if there is a good way to add tests.
=> Support user avatar file upload

lib/Gitlab/Api/GroupsBoards.php, lib/Gitlab/Client.php, test/Gitlab/Tests/Api/GroupBoardsTest.php
FYI this is more or less the same code as `IssueBoards`.
=> Add routes to manage group boards

lib/Gitlab/Api/Repositories.php, test/Gitlab/Tests/Api/RepositoriesTest.php
Add the [straight option](https://docs.gitlab.com/ee/api/repositories.html#compare-branches-tags-or-commits) for the compare api.
To keep BC, the default value is set to `false`.
=> Compare branches,tags,commits: add straight option

lib/Gitlab/Api/Issues.php, test/Gitlab/Tests/Api/IssuesTest.php
This added option allows only issues assigned to a specific person to be returned.
=> Added assignee_id to defined options

lib/Gitlab/Api/Projects.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Api/ProjectsTest.php
Implements this API method: https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members
=> Add method to retrieve all members from projects (including inherited)

lib/Gitlab/Client.php
On gitlab.com, the artifacts can be sometimes moved to Amazon S3. In this event, the call to the API will not return the artifact but will return an HTTP 302 code.
See 
- https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/5168
- https://github.com/thecodingmachine/washingmachine/issues/23#issuecomment-411488680
We need to follow this redirect to download the artifact.
The current HTTP client does not follow redirects automatically.
This PR simply adds the "RedirectPlugin" to the list of plugins of the HTTP client. Therefore, the HTTP client will follow the redirects and return the artifact as expected.
=> Adding redirect plugin for Artifact downloads

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
GitLab API allows two optional params when forking, path and name: https://docs.gitlab.com/ee/api/projects.html#fork-project
Added them to the validator so, when forking a repo, it can be renamed and placed in a different path.
=> Allow setting path and name when forking a Project

lib/Gitlab/Api/Repositories.php, test/Gitlab/Tests/Api/RepositoriesTest.php
The branches api can have an optional "search" parameter to filter for branch names
https://docs.gitlab.com/ee/api/branches.html#list-repository-branches
=> Branches API: add search attribute

lib/Gitlab/Client.php, lib/Gitlab/HttpClient/Plugin/ApiVersion.php, test/Gitlab/Tests/HttpClient/Plugin/ApiVersionTest.php
When downloading artifacts, I'm being redirected to an object store at Google. At this point the ApiVersion plugin currently adds the API version to Google's URL, which causes errors.
By keeping track of the last request, we know if it is being redirected. The following request will overwrite the last stored state. To be able to keep track of redirects, we need to be after the RedirectPlugin.
=> Fixed redirects for downloading artifacts

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
I need to search the pipelines for a sha of a specific commit. This change adds a parameter to filter the pipelines for a sha of a commit.
If you have questions or require changes, please let me know.
=> Add a SHA property/filter for pipelines

lib/Gitlab/Model/Group.php, lib/Gitlab/Model/Project.php, test/Gitlab/Tests/Model/GroupTest.php, test/Gitlab/Tests/Model/ProjectTest.php
Hello,
this PR updates the model properties for Group and Project to match the current GitLab API v4 implementation according to (it does not add all additional properties which can be fetched by accessing a single project or group):
* https://docs.gitlab.com/11.11/ee/api/groups.html#list-groups
* https://docs.gitlab.com/11.11/ee/api/projects.html#list-all-projects
For projects this removes the properties `code`, `public`, `private` and `greatest_access_level` which are not returned by the current API version.
Note: I also reordered the project properties to match the GitLab documentation to easier be able to see whether new properties were added.
=> Group + Project model properties

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
I added the additional parameters in a non-breaking way for now.
For the next major release, the API should be cleaned up and move all optional parameters into the array parameter.
=> Allow passing arbitrary additional options to MergeRequests#create()

lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/ProjectsTest.php
Resolves #461 
I started adding an OptionsResolver to validate the variables, but it doesn't appear to be possible to validate non-associative arrays of arrays. See https://github.com/symfony/symfony/issues/34207
The lack of validation does mean that it's compatible with GitLab versions pre and post 11.11.
=> Facilitate creating pipelines with variables

lib/Gitlab/Api/Wiki.php, lib/Gitlab/Client.php, lib/Gitlab/Model/Wiki.php, test/Gitlab/Tests/Api/WikiTest.php
Started by creating the API and Models for the WIKI endpoints to address the following issue. 
References https://github.com/m4tthumphrey/php-gitlab-api/issues/335
See the following API from gitlab, 
https://docs.gitlab.com/ee/api/wikis.html
Items still left to complete.
=> Created the api and models for the Wiki endpoint

lib/Gitlab/Api/Issues.php, test/Gitlab/Tests/Api/IssuesTest.php
Distinct method group() was added to Issues api route to enable getting issues for a group.
In fact, there should be 3 methods: all(), group() and project() (like in IssuesStatistics), but removing $project_id parameter from all() method now will result in a breaking change.
=> Add method to get issues for a group.

lib/Gitlab/Api/Users.php, test/Gitlab/Tests/Api/UsersTest.php
Used same parameters normalization as in Projects::all() and added similar tests.
+ fixed UsersTest::shouldShowUsersProjectsWithLimit() test.
=> Added users projects request parameters normalization.

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
The Gitlab merge request API added support for automatically rebasing the source_branch of the merge request against its target_branch (see: https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request). The code contained in this commit implements this feature.
* Add Rebase MR API call
* Add test for rebase MR
=> Implement merge request API rebase endpoint

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
The Gitlab merge request API has several optional parameters for the show single merge request API endpoint (see: https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr). The code contained in this commit implements those optional parameters EXCEPT `render_html`.
* Add optional parameters for show single MR
* Extend test for show single MR
=> Implement optional parameters for show single MR API endpoint

lib/Gitlab/Api/Issues.php
`assignee_id` is a valid parameter in GitLab's Issue API https://docs.gitlab.com/ce/api/issues.html#list-issues
It would be great, if you would allow your library to use it as filter parameter.
=> [9.18] Allow to search and find issues by "assignee_id"

lib/Gitlab/Api/MergeRequests.php, test/Gitlab/Tests/Api/MergeRequestsTest.php
Adds scope to merge request API and have made project_id optional on the merge request which was added in Gitlab 9.5:
- https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests
Carry https://github.com/m4tthumphrey/php-gitlab-api/pull/287 by @biggins
Rebased against 3050e6d
=> [9.18] Add scope and allow all projects to merge request api

lib/Gitlab/Api/MergeRequests.php, lib/Gitlab/Api/Projects.php, test/Gitlab/Tests/Api/MergeRequestsTest.php, test/Gitlab/Tests/Api/ProjectsTest.php
This PR add methods for these API endpoints:
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-configuration
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-project-level-rules
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-the-approval-state-of-merge-requests
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-merge-request-level-rules
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-merge-request-level-rule
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#update-merge-request-level-rule
* https://docs.gitlab.com/ee/api/merge_request_approvals.html#delete-merge-request-level-rule
=> [9.18] Add some methods related to merge requests approvals

lib/Gitlab/Model/Commit.php
So, when I'm trying to get list of commits with 'with_stats' property - the array 'stats' which Gitlab returns dissapears because no such property added.
=> [9.18] Adding 'stats' property to Commit model
