README.md

Added Laravel integration and updated copy.

Update Framework Integrations

---

lib/Gitlab/Model/Project.php
lib/Gitlab/Model/User.php

Hi,
sorry, I have been buried in work. I have added another function.
I have rebased the repo, this time everything should be ok.
Thanks, regards

Added CreateProject for user and CreateKey for User

---

lib/Gitlab/Api/Users.php
lib/Gitlab/Model/User.php
test/Gitlab/Tests/Api/UsersTest.php

Gitlab 7.13 API allow to block / unblock users: https://gitlab.com/help/api/users.md#block-user

Add support for block/unblock users

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

Add support to get the builds of a project.

Add builds to Project API.

---

lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/RepositoriesTest.php

Add support to fetch the builds for a specific commit through the Repository API.

Add commit builds to Repository API

---

.travis.yml

I just tried on my local machine and tests with php7 are running fine

Add tests for php7

---

lib/Gitlab/Api/Repositories.php

Added repository/archive endpoint to download the full archive of the repository

Added repository/archive endpoint

---

lib/Gitlab/Api/AbstractApi.php
lib/Gitlab/Api/ApiInterface.php
lib/Gitlab/Api/Issues.php
lib/Gitlab/Client.php
lib/Gitlab/HttpClient/Listener/PaginationListener.php
lib/Gitlab/HttpClient/Message/Response.php
lib/Gitlab/ResultPager.php
lib/Gitlab/ResultPagerInterface.php
test/Gitlab/Tests/Api/IssuesTest.php

via a PaginatorListener
and fixed issue fetching within a project, due to API changes

added Result Paginator

---

lib/Gitlab/Api/AbstractApi.php
lib/Gitlab/Api/Projects.php
lib/Gitlab/HttpClient/HttpClient.php
lib/Gitlab/HttpClient/HttpClientInterface.php
lib/Gitlab/HttpClient/Message/FormRequest.php
test/Gitlab/Tests/Api/AbstractApiTest.php

Implements http://docs.gitlab.com/ce/api/projects.html#uploads

Upload a file in a project

---

lib/Gitlab/Api/Projects.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/ProjectsTest.php

Added the archive/unarchive functionality as requested in issue #141

Add archive/unarchive functionality

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

This PR adds `deployments` API to `projects` API.

Added project deployments API

---

lib/Gitlab/Api/MergeRequests.php

merge_request -> merge_requests
introduced in #169

fixed wrong path in addNote method

---

lib/Gitlab/Api/Issues.php
test/Gitlab/Tests/Api/IssuesTest.php

This completes the time tracking feature set, by adding the missing methods to:
* Set time estimate
* Reset time estimate
* Add spent time
* Reset spent time
Tests included.

Time tracking features

---

lib/Gitlab/Model/Node.php
test/Gitlab/Tests/Api/ProjectsTest.php

Added path to list of properties in Node model & Fixed failing ProjectTest

Adding of path to list of properties in Node Model

---

lib/Gitlab/Api/MergeRequests.php

I merged #201 before @fbourigault could review it, so I've made another PR with the changes he requested. Sorry!

Apply #201 suggested fixes

---

lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/RepositoriesTest.php

This apply API changes introduced by https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8936.

Rename branch_name to branch

---

lib/Gitlab/Api/Projects.php

Changes from https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8940.

Project fork v4 compatibility

---

lib/Gitlab/Api/Users.php
test/Gitlab/Tests/Api/UsersTest.php

Changes from https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9371.

Compatibility with v4 api for Users::block and Users::unblock

---

UPGRADE.md
lib/Gitlab/Api/Projects.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/ProjectsTest.php

Handle changes from [!8716](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8716) and [!9366](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9366.)
I tried to document all breaking changes. A careful review on this point would be welcome!

Remove deprecated keys project endpoints

---

UPGRADE.md
lib/Gitlab/Model/Snippet.php

Changes from [!8723](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8723).

remove expires_at snippet property

---

lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/RepositoriesTest.php

Changes for [!9637](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9637)

update files repository endpoint for v4

---

UPGRADE.md
lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/RepositoriesTest.php

Changes for [!9679](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9679).

commits repository v4 api changes

---

.styleci.yml
lib/Gitlab/Api/AbstractApi.php
lib/Gitlab/Api/Projects.php
lib/Gitlab/Api/Repositories.php
lib/Gitlab/Client.php
lib/Gitlab/Exception/ErrorException.php
lib/Gitlab/Exception/InvalidArgumentException.php
lib/Gitlab/Exception/RuntimeException.php
lib/Gitlab/Exception/ValidationFailedException.php
lib/Gitlab/Model/Group.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/RepositoriesTest.php
test/Gitlab/Tests/HttpClient/BuilderTest.php
test/Gitlab/Tests/HttpClient/Plugin/ApiVersionTest.php
test/Gitlab/Tests/ResultPagerTest.php

Update coding standards to PSR-2.

---

lib/Gitlab/Model/Issue.php

use iid instead id on Issue model.

---

README.md

Updated the Laravel integration link.

Update Laravel link

---

lib/Gitlab/Api/Repositories.php

Similar to https://github.com/m4tthumphrey/php-gitlab-api/pull/232

Add pagination to load tags

---

lib/Gitlab/Api/Issues.php
lib/Gitlab/Api/MergeRequests.php
lib/Gitlab/Api/Snippets.php
test/Gitlab/Tests/Api/IssuesTest.php
test/Gitlab/Tests/Api/MergeRequestsTest.php
test/Gitlab/Tests/Api/SnippetsTest.php

> Introduced in GitLab 8.9, Snippet support in 8.12
> https://docs.gitlab.com/ce/api/award_emoji.html

Add award emoji

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

invalid link for pipeline creation
see gitlab documentation: https://docs.gitlab.com/ce/api/pipelines.html#create-a-new-pipeline

fix link for pipeline creation

---

lib/Gitlab/Api/Repositories.php

Example: usefull to set the per_page param
Otherwise this method only respond with a maximum of 20 branches

adding parameters on repositories->branches 

---

lib/Gitlab/Api/Projects.php

add params id fork

---

.travis.yml
composer.json

Allow symfony/options-resolver ^4.0

---

lib/Gitlab/Api/Deployments.php
lib/Gitlab/Api/Environments.php
lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/DeploymentsTest.php
test/Gitlab/Tests/Api/EnvironmentsTest.php

Added basic support for fetching information about Deployments and Environments, since we needed this information in one of our deploy tools.

Add support for Deployments and Environments api

---

lib/Gitlab/Api/Version.php
lib/Gitlab/Client.php
test/Gitlab/Tests/Api/VersionTest.php

https://docs.gitlab.com/ee/api/version.html

Version: add api endpoint

---

composer.json

Switched to PHPUnit 5

---

lib/Gitlab/Exception/ErrorException.php
lib/Gitlab/Exception/ExceptionInterface.php
lib/Gitlab/Exception/InvalidArgumentException.php
lib/Gitlab/Exception/MissingArgumentException.php
lib/Gitlab/Exception/RuntimeException.php
lib/Gitlab/Exception/ValidationFailedException.php

Mimics [KnpLabs/php-github-api@2.7.0 Github\Exception\ExceptionInterface.php](https://github.com/KnpLabs/php-github-api/blob/2.7.0/lib/Github/Exception/ExceptionInterface.php).
---
Closes #298.

Added exception interface

---

README.md

@vinkla has retired his package, and I took the opertunity to start again, and write another package.
---
Old: https://github.com/vinkla/laravel-gitlab
New: https://github.com/GrahamCampbell/Laravel-GitLab

Replaced laravel integration link

---

lib/Gitlab/Api/Projects.php

members request does not require query and is actually broken right now if you provide an empty query
https://gitlab.com/gitlab-com/support-forum/issues/2878

fix members request with empty query.

---

lib/Gitlab/Api/Users.php
test/Gitlab/Tests/Api/UsersTest.php
test/Gitlab/Tests/HttpClient/BuilderTest.php

I didn't found users project method and decide to add it, could you check it please.
I have done: 
added get user's projects feature.
added unit test for it.

add get user's projects feature.

---

lib/Gitlab/Api/Snippets.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/SnippetsTest.php

Add required param visibility for creation of snippets.
#294 close

Add snippet visibility for creating

---

lib/Gitlab/Api/Projects.php

https://docs.gitlab.com/ee/api/projects.html#share-project-with-group

add share functionality

---

lib/Gitlab/Api/Groups.php
lib/Gitlab/Model/Group.php
test/Gitlab/Tests/Api/GroupsTest.php

https://docs.gitlab.com/ee/api/groups.html#list-a-groups-39-s-subgroups

Groups: add subgroup endpoint

---

lib/Gitlab/Client.php
lib/Gitlab/Model/Issue.php
test/Gitlab/Tests/Model/IssueTest.php

- Add hasLabel method for Issue model
- Remove duplicate environments() method in `lib/Gitlab/Client.php`

Add hasLabel method to Issue model

---

lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/RepositoriesTest.php

This builds on PR #336, adding a test, and slightly improving whitespace & capitalization.

Add a method to pull refs (tags and branches) for a given commit, with a test

---

test/Gitlab/Tests/Api/TagsTest.php

This should get the tests closer to passing again.

Update tests added by c272ba7 to call methods with better arguments

---

lib/Gitlab/Model/Release.php
lib/Gitlab/Model/Tag.php
test/Gitlab/Tests/Model/ReleaseTest.php

These changes are for https://github.com/m4tthumphrey/php-gitlab-api/issues/375.
Please, accept them if everything allright, so we can get release notes and tags mesages. Thanks

Tag message and release properties

---

lib/Gitlab/Api/Issues.php
lib/Gitlab/Api/MergeRequests.php
test/Gitlab/Tests/Api/IssuesTest.php
test/Gitlab/Tests/Api/MergeRequestsTest.php

Support of Discussion API for issues and merge requests
https://docs.gitlab.com/ce/api/discussions.html

Support of Discussion API for issues and merge requests

---

lib/Gitlab/Api/Milestones.php
test/Gitlab/Tests/Api/MilestonesTest.php

https://docs.gitlab.com/ce/api/milestones.html#delete-project-milestone

Delete project milestone method

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

I needed for a project list the project issues and boards , this PR add the neccesary methods to make it works. Please review, Thanks!

Add methods to get project issues and project boards

---

lib/Gitlab/Api/AbstractApi.php
lib/Gitlab/Api/GroupsMilestones.php
lib/Gitlab/Client.php
test/Gitlab/Tests/Api/GroupsMilestonesTest.php

Add GroupsMilestones routes

---

README.md

Small enhancement  

---

lib/Gitlab/Model/Group.php
test/Gitlab/Tests/Model/GroupTest.php

Model Group projects should return Projects

---

lib/Gitlab/Api/Groups.php
test/Gitlab/Tests/Api/GroupsTest.php

* List group variables
* Show group variable details
* Create group variable
* Update group variable
* Remove group variable

Add methods to manage group level variables

---

.gitignore
lib/Gitlab/Api/Schedules.php
lib/Gitlab/Client.php
lib/Gitlab/Model/Schedule.php
test/Gitlab/Tests/Api/ScheduleTest.php

this PR adds #405 features.
Create, update, show and delete Schedules on CI.

create, update, show and delete schedules

---

lib/Gitlab/Api/Projects.php
lib/Gitlab/Model/Badge.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/ProjectsTest.php

Implements `Project->Badges` API  
https://docs.gitlab.com/ee/api/project_badges.html
test included

Add project badges API

---

lib/Gitlab/Api/Groups.php
lib/Gitlab/Api/GroupsMilestones.php
lib/Gitlab/Api/Issues.php
lib/Gitlab/Api/MergeRequests.php
lib/Gitlab/Api/Milestones.php
lib/Gitlab/Api/Projects.php
lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/GroupsTest.php

https://docs.gitlab.com/ee/api/group_labels.html

Provide Group Labels API

---

lib/Gitlab/Api/Repositories.php
test/Gitlab/Tests/Api/RepositoriesTest.php

Adds API method to call endpoint to list releases: https://docs.gitlab.com/ee/api/releases/index.html#list-releases

Add ability to list releases.

---

lib/Gitlab/Model/Note.php

Sorry for such a small change. But my PHPStan started complaining.
Signed-off-by: Ted van Riel <tvanriel@wendrich.com>

Add missing property read to Note.php

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

Delete a pipeline. 
https://docs.gitlab.com/ee/api/pipelines.html#delete-a-pipeline

Added deletePipeline() method

---

lib/Gitlab/Api/Projects.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/ProjectsTest.php

https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches 
This was my method for allowing the ability to have more control of the permissions that I Mentioned in #440.

Addition of addProtectedBranch method per updates to protect branch API

---

lib/Gitlab/Model/Label.php
test/Gitlab/Tests/Api/GroupsTest.php
test/Gitlab/Tests/Api/ProjectsTest.php
test/Gitlab/Tests/Model/LabelTest.php

https://github.com/m4tthumphrey/php-gitlab-api/issues/446

#446 - label model id

---

lib/Gitlab/Api/Groups.php
test/Gitlab/Tests/Api/GroupsTest.php

Added the following attributes for groups projects
- with_issues_enabled
- with_merge_requests_enabled
- with_shared
- with_shared
- with_custom_attributes

#422 Added attributes for groups projects

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

Hi. 
This method allow getting project users from api: https://docs.gitlab.com/ee/api/projects.html#get-project-users
Can you check, and if correct merge to master? Thank you!

Add method to obtain project users

---

.travis.yml

use php 7.3 and not-outdated dependencies for phpstan

---

.travis.yml
composer.json
phpunit.xml.dist
test/Gitlab/Tests/ResultPagerTest.php

This PR adds PHP 7.4 support (no changes needed in src).

PHP 7.4 Support

---

lib/Gitlab/Api/Projects.php

Fixed projects updateBadge PUT call, now includes body parameters

---

lib/Gitlab/Api/Environments.php
test/Gitlab/Tests/Api/EnvironmentsTest.php

implemented Environments::show()

---

lib/Gitlab/Api/Projects.php
lib/Gitlab/Api/Users.php
test/Gitlab/Tests/Api/UsersTest.php

I have only 20 userprojects, for params per_page i needed options in this. Maybe somebody will use it

adding params for userprojects

---

lib/Gitlab/Api/Issues.php
test/Gitlab/Tests/Api/IssuesTest.php

Implemented method to get issue participants (Issues::showParticipants) with basic test.

Implemented Issues::showParticipants.

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

I need all forks of a project, but this Call was missing. Please add.
Thanks
Philipp

add forks API call to return all forked projects

---

lib/Gitlab/Api/Projects.php
test/Gitlab/Tests/Api/ProjectsTest.php

For more details: https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines

Added /projects/:id/pipelines fields [updated_after, updated_before]

---

.gitattributes

This commit is part of a campaign to reduce the amount of data transferred to save global bandwidth and reduce the amount of CO2. See https://github.com/Codeception/Codeception/pull/5527 for more info.

[9.18] Ignore files when exporting package

---

lib/Gitlab/Api/Repositories.php

[9.18] Fixed typo

---

lib/Gitlab/Api/Issues.php
test/Gitlab/Tests/Api/IssueSubscribeTest.php

Fixes https://github.com/m4tthumphrey/php-gitlab-api/issues/491

[9.18] Add subscribe/unsubscribe methods to issue api

---

lib/Gitlab/Api/Issues.php

Now Issue can resolve more option as listed in the documentation created_after, created_before, updated_after, updated_before

[9.18] Updated Issues to support updated_after

---

lib/Gitlab/Api/Groups.php
lib/Gitlab/Api/Projects.php
lib/Gitlab/Model/Group.php
lib/Gitlab/Model/Project.php
test/Gitlab/Tests/Api/GroupsTest.php
test/Gitlab/Tests/Api/ProjectsTest.php

Reverts https://github.com/m4tthumphrey/php-gitlab-api/pull/492.

[9.18] Revert broken PR
